export const CHANGE_SEARCH_FIELD = "CHANGE_SEARCH_FIELD";

export const REQUEST_ROBOTS_PENDING = "REQUEST_ROBOTS_PENDING";
export const REQUEST_ROBOTS_SUCCESS = "REQUEST_ROBOTS_SUCCESS";
export const REQUEST_ROBOTS_FAILED = "REQUEST_ROBOTS_FAILED";

export const REQUEST_LOCAL_INVOICES_PENDING = "REQUEST_LOCAL_INVOICES_PENDING";
export const REQUEST_LOCAL_INVOICES_SUCCESS = "REQUEST_LOCAL_INVOICES_SUCCESS";
export const REQUEST_LOCAL_INVOICES_FAILED = "REQUEST_LOCAL_INVOICES_FAILED";
